services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672" # AMQP protocol (used by the app)
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
